# -*- coding: utf-8 -*-
"""Curso_Basico_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rjdN5YLG-vBG2jMKTkdtkWVYaIxW_0nc

**Passo a Passo de solução do Desafio**
"""

#conexão ao drive
from google.colab import drive
drive.mount('/content/drive')

#importando as bibliotecas e lendo os arquivos
import os
import pandas as pd

lista_arquivo = os.listdir("/content/drive/MyDrive/curso automação/Vendas/Vendas")
display(lista_arquivo)

#Fazendo junção de todas as tabelas pegando somente as vendas
tabela_total = pd.DataFrame()

for arquivo in lista_arquivo:
 if "Vendas" in arquivo:
   tabela = pd.read_csv(f"/content/drive/MyDrive/curso automação/Vendas/Vendas/{arquivo}")
   tabela_total = tabela_total.append(tabela)


display(tabela_total)

# calculando o produto mais ventido

tabela_produtos = tabela_total.groupby("Produto").sum()
tabela_produtos = tabela_produtos[["Quantidade Vendida","Preco Unitario"]].sort_values(by="Quantidade Vendida", ascending = False)
display(tabela_produtos)

#fazendo calculo de faturamento e adicionando uma nova tabela chamada de faturamento

tabela_total['Faturamento'] = tabela_total["Quantidade Vendida"] * tabela_total["Preco Unitario"]

tabela_faturamento = tabela_total.groupby("Produto").sum()
tabela_faturamento = tabela_faturamento[["Faturamento"]].sort_values(by="Faturamento", ascending = False)
display(tabela_faturamento)

#loja com maior numero de venda de acordo com o faturamento
tabela_lojas = tabela_total.groupby("Loja").sum()
tabela_lojas = tabela_lojas[['Faturamento']]
display(tabela_lojas)

#dashoboard das lojas com maior faturamento
import plotly.express as px 

grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()